services:
  db:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: auth_db
    volumes:
      - ~/apps/postgres/spring-auth-service:/var/lib/postgresql/data
    networks:
      - backend_net

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_PASSWORD: admin@123
    networks:
      - backend_net

  api:
    container_name: auth_service_api
    build: ./Api/spring-auth-service
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge