services:
  db:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: auth_db
    volumes:
      - ~/apps/postgres/spring-auth-service:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_PASSWORD: admin@123