spring:
  application:
    name: spring-auth-service
  mvc:
    problemdetails:
      enabled: true

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# Database connection
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin@123
    url: jdbc:postgresql://localhost:5432/auth_db?createDatabaseIfNotExist=true

# Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: admin@123

application:
# Jwt Configuration
  jwt:
    config:
      encryption-key: 5heUCJxsTsaYyTE6+XB+tnpvdZkttNv5PBWHe9v9q73kGjDa2+UI2YQMWPj1Fpec
      # Expiration in milliseconds
      token-expiration: 600000 # 10 minutes
      refresh-token-expiration: 604800000 # 7 days

# Verification Token Config
  verification-token:
    # Expiration in milliseconds
    expiration: 1800000 # 30 minutes


# Mail Configuration
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: c405f4c0a04209
    password: 321482787ddcf7
    sender: no-reply@example.com