spring:
  # Database connection
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin@123
    url: jdbc:postgresql://postgresql:5432/auth_db?createDatabaseIfNotExist=true

  # Redis
  data:
    redis:
      host: redis
      port: 6379
      password: admin@123