spring:
  profiles:
    active: prod
  application:
    name: spring-auth-service
  mvc:
    problemdetails:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

# Liquibase Configuration
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

application:
# Jwt Configuration
  jwt:
    config:
      encryption-key: 5heUCJxsTsaYyTE6+XB+tnpvdZkttNv5PBWHe9v9q73kGjDa2+UI2YQMWPj1Fpec
      # Expiration in milliseconds
      token-expiration: 600000 # 10 minutes
      refresh-token-expiration: 604800000 # 7 days

# Verification Token Config
  verification-token:
    # Expiration in milliseconds
    expiration: 1800000 # 30 minutes