spring:
  application:
    name: spring-auth-service
  mvc:
    problemdetails:
      enabled: true

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# Database connection
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin@123
    url: jdbc:postgresql://localhost:5432/auth_db?createDatabaseIfNotExist=true

# Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: admin@123

application:
# Jwt Configuration
  jwt:
    config:
      encryption-key: 5heUCJxsTsaYyTE6+XB+tnpvdZkttNv5PBWHe9v9q73kGjDa2+UI2YQMWPj1Fpec
      token-expiration: 600000 # 10 minutes
      refresh-token-expiration: 604800000 # 7 days